"""create db

Revision ID: 5fed32584f43
Revises: 
Create Date: 2024-03-27 17:09:03.805628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fed32584f43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('zip')
    )
    op.create_index(op.f('ix_location_zip'), 'location', ['zip'], unique=False)
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location_zip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_zip'], ['location.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_zip', sa.Integer(), nullable=True),
    sa.Column('delivery_zip', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_zip'], ['location.zip'], ),
    sa.ForeignKeyConstraint(['pickup_zip'], ['location.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_location_zip'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
